apiVersion: v1
kind: ServiceAccount
metadata:
  name: seccompagent
  namespace: kube-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: seccompagent
subjects:
- kind: ServiceAccount
  name: seccompagent
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: seccompagent
  namespace: kube-system
  labels:
    k8s-app: seccompagent
spec:
  selector:
    matchLabels:
      k8s-app: seccompagent
  template:
    metadata:
      labels:
        k8s-app: seccompagent
    spec:
      serviceAccount: seccompagent
      hostPID: true
      containers:
      - name: seccompagent
        image: quay.io/kinvolk/seccompagent:alban_opa
        command: [ "/bin/seccompagent", "-resolver=opa", "-log=trace" ]
        imagePullPolicy: Always
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        securityContext:
          capabilities:
            add:
            # CAP_SYS_PTRACE is useful to read arguments of a processes with
            # the prctl PR_SET_DUMPABLE bit set to zero.
            - "SYS_PTRACE"
            # CAP_SYS_ADMIN is useful to setns in containers and mount
            - "SYS_ADMIN"
            - "NET_ADMIN"
          # privileged: true
        volumeMounts:
        - name: seccomp-policies
          mountPath: /host/seccomp
        - name: run
          mountPath: /run
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
      volumes:
      - name: seccomp-policies
        hostPath:
          path: /var/lib/kubelet/seccomp
      - name: run
        hostPath:
          path: /run
