apiVersion: v1
kind: ServiceAccount
metadata:
  name: seccompagent
  namespace: kube-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: seccompagent
subjects:
- kind: ServiceAccount
  name: seccompagent
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: seccomp-agent-rego
  namespace: kube-system
data:
  example.rego: |
    package example.authz
    default allow = false
    allow {
        input.syscall = "execve"
    }
    allow {
        input.syscall = "mkdir"
        input.arg0 = "abc"
    }
    allow {
        input.syscall = "mkdir"
        startswith(input.arg0, "foo")
        input.pod.namespace = "default"
        input.pod.pod = "mynotifypod"
        input.pod.container = "container1"
    }
    default handler_MkdirWithSuffix = false
    handler_MkdirWithSuffix {
        input.syscall = "mkdir"
        endswith(input.arg0, "--")
    }
    #default handler_Mount = false
    #handler_Mount {
    #    input.syscall = "mount"
    #    input.arg0 = "proc")
    #}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: seccompagent
  namespace: kube-system
  labels:
    k8s-app: seccompagent
spec:
  selector:
    matchLabels:
      k8s-app: seccompagent
  template:
    metadata:
      labels:
        k8s-app: seccompagent
    spec:
      serviceAccount: seccompagent
      hostPID: true
      containers:
      - name: seccompagent
        image: quay.io/kinvolk/seccompagent:alban_opa
        command: [ "/bin/seccompagent", "-resolver=opa", "-log=trace" ]
        imagePullPolicy: Always
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        securityContext:
          capabilities:
            add:
            # CAP_SYS_PTRACE is useful to read arguments of a processes with
            # the prctl PR_SET_DUMPABLE bit set to zero.
            - "SYS_PTRACE"
            # CAP_SYS_ADMIN is useful to setns in containers and mount
            - "SYS_ADMIN"
            - "NET_ADMIN"
          # privileged: true
        volumeMounts:
        - name: seccomp-policies
          mountPath: /host/seccomp
        - name: run
          mountPath: /run
        - name: seccomp-agent-rego
          mountPath: /etc/seccomp-agent
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
      volumes:
      - name: seccomp-policies
        hostPath:
          path: /var/lib/kubelet/seccomp
      - name: run
        hostPath:
          path: /run
      - name: seccomp-agent-rego
        configMap:
          name: seccomp-agent-rego
